### ISSUE TITLE
Visual Feedback Bugs

### ISSUE THREAD

**Issue by BenjaminWynn** [charlieroberts/gibber.max#25]
1. 
I’ve noticed a persistent bug with the graph displays for visual feedback. It consistently removes the comma or bracket right before the space it enters. So for example this:
`l.start.seq( [2.015,3.8,4], 2 ).clear()` 
turns into this:
`l.start.seq( [2.015,3.8,4] 2 ).clear()`
It then creates  errors upon the next evaluation.

2.
I don't get visual feedback for messages like this:
`message( 'ratio' ).seq( [1, 1.5, 1.48], [4,1.8,3] )`
but I do for params:
`params[ 'Slew' ].seq( [820, 1400, 3500], [4,1.8,3] ) `

**Comment by kingumfufu** [comment]
I don't get visual feedback for messages like this:
`message( 'ratio' ).seq( [1, 1.5, 1.48], [4,1.8,3] )`
but I do for params:
`params[ 'Slew' ].seq( [820, 1400, 3500], [4,1.8,3] )`

**Comment by charlieroberts** [comment]
Number 2 is fixed in https://github.com/gibber-cc/gibberwocky/commit/544f0dc58d1361cd4e27baa6cb7910c5391669c5

**Comment by charlieroberts** [comment]
will tackle number 1 tomorrow and then push to the main web editor.

**Comment by BenjaminWynn** [comment]
Amazing. Thank you!!

Also, I'm not sure if it's a bug but I've been exploring the amazing score functionality and I noticed that there isn't any visual feedback there. Is that intentional?

**Comment by charlieroberts** [comment]
I had working visual annotations for `Score` in gibber at some point—and it was actually really cool and useful—but I don't think I've ever had them working in gibberwocky. Probably worth opening a different ticket... I'd like to close this one after fixing these two bugs. Thanks!

**Comment by BenjaminWynn** [comment]
Sounds good thanks.
Will do!

**Comment by charlieroberts** [comment]
So, oddly, I can't recreate the behavior of problem 1, even though I know I've seen this before. Can you post a more complete example? I keep running this:

```js
l = line(4,0,1)
params['White_Queen'].seq( l,1/4 )
l.start.seq( [0,.1,.2], 1/2 )
```

... and no matter how many times I clear/re-execute it I don't get that bug with the comma disappearing.

**Comment by BenjaminWynn** [comment]
Oddly it's not happening for me any more either. Their used to be a graph that would pop up on `l.start.seq` but it's not anymore. Maybe that was a bug that it was showing up at all there? I've annotated the code below. Let me know if you'd like more code!

```
l = line( 4,1, 1.05 )
message( 'ratio' ).seq( l, 2  )
l.start.seq( [2.015,3.8,4], 2 ) -- there used to be a graph that popped up in between the end of the array and the "2". It's not showing up anymore. 
l.period.seq( [3,1], 1 )
```

**Comment by BenjaminWynn** [comment]
BTW I'm still not getting visual feedback on this message command below, but I am for the `params` one:

```
message( 'ratio' ).seq( [1, 1.5, 1.48], [4,1.8,3] )
params[ 'Slew' ].seq( [820, 1400, 3500], [4,1.8,3] )
```

**Comment by charlieroberts** [comment]
I haven't pushed to the web editor... did you download the repo to test this? Otherwise we should be good to go and I'll upload to gibberwocky.cc/burble shortly.

Maybe something I did to fix the `message()` related bug fixed the other problem. Sweet.

**Comment by BenjaminWynn** [comment]
Ah, no, I'd assumed that the fix would show up already. Got it.
And yeah, maybe the other one is fixed as well! I'll let you know if I see it again. Thanks.

**Comment by charlieroberts** [comment]
OK, it's live on the web now!

**Comment by charlieroberts** [comment]
make sure to force reload the page (cmd+shift+r in chrome)

**Comment by BenjaminWynn** [comment]
Seeing the message visuals thank you!
